apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-postgres
  namespace: ${K8S_NAMESPACE}
  labels:
    app: ${APP_NAME}-postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: ${APP_NAME}-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
